### PR TITLE
Change to chain.from_iterable in truecase.py

### PR DESCRIPTION
**Pull request by cool-RR**
This one might be a better candidate :)

### CODE REVIEW

**Comment by alvations** [comment]
In both cases, there's no real performance improvements

**Comment by alvations** [comment]
I think it's worth while to prove that change is necessary. Esp. if it is so, understand why did Python allow both functions to exists. 

First, we have to validate when does the no. of elements in the outer-loop of in the list of list of things matters.

**Comment by alvations** [comment]
Lets try this:

```python
import random
from functools import wraps
from time import time

def timing(f):
    @wraps(f)
    def wrap(*args, **kw):
        ts = time()
        result = f(*args, **kw)
        te = time()
        print('func:%r args:[%r, %r] took: %2.4f sec' % (f.__name__, args, kw, te-ts))
        return result
    return wrap

def generate_nm(n, m):
    # Creates n generators of m integers between range 0 to 1000000.
    yield iter(random.sample(range(m), m) for _ in range(n))
    

def chain_star(x):
    # Stores an iterable that will unpack and flatten the list of list.
    chain_x = chain(*x)
    # Consumes the items in the flatten iterable.
    for i in chain_x:
        pass

def chain_from_iteratble(x):
    # Stores an iterable that will unpack and flatten the list of list.
    chain_x = chain.from_iterable(x)
    # Consumes the items in the flatten iterable.
    for i in chain_x:
        pass

@timing
def versus(f):
    for i in range(1, 1001):
        for j in range(1, 1001):
            chain_star(generate_nm(i, j))
````

**Comment by cool-RR** [comment]
> I think it's worth while to prove that change is necessary.

It's definitely not necessary. It's an esoteric optimization, and I'd understand if you'd reject it. 

> Esp. if it is so, understand why did Python allow both functions to exist.

There are very good reason for that:

1. It's meaningfully faster if the iterable takes a long time to produce its items.
2. It's meaningfully faster if the iterable has a long number of items.
3. If the iterator is infinite, it's the only way chaining would work, because `chain(*iterable)` would hang.

**Comment by alvations** [comment]
It's good to understand the claims using the benchmarking code above and see  how far it goes so that it's documented and even put onto [this stackoverflow question/answer](https://stackoverflow.com/questions/15004772/what-is-the-difference-between-chain-and-chain-from-iterable-in-itertools) if necessary =)

**Comment by cool-RR** [comment]
> I think this might be true for both `chain(*iterable)` and `chain.from_iterable(iterable)`. Lets wait for the benchmarking to finish and see how it works out.

That's definitely false. This code hangs until the company is out of memory:

```python
>>> for i in itertools.chain(*(range(10) for _ in itertools.count())):                               
...   print(i)                                                                                       
...                                                                                                  
```

While the equivalent with `chain.from_iterable` succeeds, and can run indefinitely without increasing memory usage. (Well, until it hits the maximum int limitation.) 

In any case, this is more research than I want to do, sorry :( Thanks for your time and attention so far.

**Comment by alvations** [comment]
It's good to take a deeper look at the details esp. if this change from `chain(*...)` is to be made for more than just this sacremoses library.

If it is true that one function does the same as the other and has no drawbacks then the language Python itself should deprecate the lesser one 😁

**Comment by alvations** [comment]
After more digging, https://github.com/python/cpython/pull/20871 seems related.

**Comment by cool-RR** [comment]
Good luck with that. Keep in mind that your script doesn't seem to account
for iterable that take a long time to produce items.

Also, in theory it would be possible to make `chain.from_iterable` be the
default behavior, but it won't happen because of backward compatibility.
It's Python 4 material.

**Comment by alvations** [comment]
After some thinking (and less coding), I think there's a case for materializing the outer loop and the code snippet for 

```python
from itertools import chain, count

for i in chain(*(range(10) for _ in count())):
    print(i)                                                                                                
```

isn't the right way to evaluate the both `chain(*...)` and `chain.from_iterable(...)`:

The outer tuple creation would have been evaluated from the `(...)` comprehension first.

```python
(range(10) for _ in itertools.count()) 
```

And it would have already resulted in the infinite loop since the `itertools.count()` is basically a `while True` loop with a counter. In that case the outer tuple creation would be evaluated by the interpreter first before calling the asterisk operation to unpack.

So technically, the same function call that evaluates the outer tuple equivalent to the `chain(*...)` would be:

```python
from itertools import chain, count

for i in chain.from_iterable( (range(10) for _ in count()) ):
    print(i)
```

And yes, the snippet above does show that `chain.from_iterable( (range(10) for _ in count()) )` works!!

But if we go and question whether it is the default chaining function that's sub-optimal or that the unpacking requires the knowledge of no. of args in the tuple to be evaluated, we see that the following fails:

```python
from itertools import chain, count
for i in chain.from_iterable(*(range(10) for _ in count())):
    print(i)
```

As like the `chain(*...)` example, ergo it is the usage of * unpacking that's causing the case where it can't cover the cases of lazily evaluating the outer iterable on-the-go and not the implementation of the default `chain` versus `chain.from_iterable`.

**Comment by alvations** [comment]
Closing this issue for now. Thanks again @cool-RR for the deeper dive into the `itertools.chain` =)

**Comment by cool-RR** [comment]
I appreciate the dive. Now let's do the same for itertools.starmap!

Jk ☺️

**Pull request closed without merging**
